eureka:
  instance:
     preferIpAddress: true
  client:
    serviceUrl:
       defaultZone: http://microservices-refapp-eureka-chrisking.mybluemix.net/eureka/

# Server configuration
server:
  context-path: /micro
  port: 8081

# Spring properties
spring:
  application:
     name: catalog-microservice

# Elasticsearch
elasticsearch:
  url: http://localhost:9200
  user:
  password:
  index: api
  doc_type: items
