apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
    app: bluecompute
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    tier: backend
    micro: catalog
type: Opaque
data:
  binding: {{ cat `{"uri": "http://` .Chart.Name `:9200/" }` | nospace | b64enc }}