apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: bluecompute
        tier: backend
        micro: catalog
    spec:
      containers:
      - name: catalog
        image: registry.ng.bluemix.net/chrisking/catalog:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: elastic
          valueFrom:
            secretKeyRef:
              name: binding-refarch-compose-for-elasticsearch
              key: binding