apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  labels: 
    app: bluecompute
    tier: backend
    micro: catalog
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  selector: 
    app: bluecompute
    tier: backend
    micro: catalog