apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: inventory-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: bluecompute
        tier: backend
        micro: inventory
    spec:
      containers:
      - name: inventory
        image: registry.ng.bluemix.net/chrisking/inventory:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: elastic
          valueFrom:
            secretKeyRef:
              name: binding-refarch-compose-for-elasticsearch
              key: binding
        - name: mysql
          valueFrom:
            secretKeyRef:
              name: binding-refarch-compose-for-mysql
              key: binding
        - name: messagehub
          valueFrom:
            secretKeyRef:
              name: binding-refarch-messagehub
              key: binding