apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
    app: bluecompute
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    tier: backend
    micro: inventory
type: Opaque
data:
  mysql-root-password:  {{ .Values.rootPassword | b64enc | quote }}
  mysql-password:  {{ .Values.password | b64enc | quote }}
  binding: {{ cat `{"uri": "mysql://` .Values.user `:` .Values.password `@` .Chart.Name `:3306/` .Values.database `" }` | nospace | b64enc }}