apiVersion: v1
kind: Service
metadata:
  name: inventory-mysql
  labels:
    app: bluecompute
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    tier: backend
    micro: inventory
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: bluecompute
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    tier: backend
    micro: inventory