apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    tier: backend
    micro: inventory
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector: 
    app: "{{ .Chart.Name }}"
    tier: backend
    micro: inventory