replicaCount: 3

registry:
  name: ibmcase

image:
  pullPolicy: IfNotPresent
  tag: 5

elasticsearch:
  serviceName: refarch-compose-for-elasticsearch
  servicePlan: Standard
  secret: binding-refarch-compose-for-elasticsearch

mysql:
  serviceName: refarch-compose-for-mysql
  servicePlan: Standard
  secret: binding-refarch-compose-for-mysql

messagehub:
  serviceName: refarch-messagehub
  servicePlan: standard
  secret: binding-refarch-messagehub